### PR TITLE
Update scala 2.13.0-RC1 to 2.13.0-RC2

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by Philippus** [comment]
closing, since I think it's not complete and `2.13.0-RC3` is out already.

**Comment by gzoller** [comment]
All good.  I may not bother re-upping each ScalaJack release for each 2.13 RC until final GA release, as I wouldn't anticipate meaningful changes.  However... that said, if there's a major 2.13 RC change that affects what you're doing, do re-submit a PR and I'll get it in!

**Comment by Philippus** [comment]
Upgrading could be interesting. I'm getting a `java.util.NoSuchElementException: head of empty list` error in https://github.com/gzoller/ScalaJack/blob/master/core/src/main/scala-2.13.0-RC1/co.blocke.scalajack/compat/CanBuildFromTypeAdapter.scala#L26

**Comment by gzoller** [comment]
Hmm, that does sound like something to take a look at.  First thing I'll check is the directory name: /scala-2.13.0-RC1.  It may need to be renamed to reflect RC3.  I think the dir name is significant (sbt chooses version-specific code based on this).

**Comment by gzoller** [comment]
6.0.2 with RC3 support has been released.  They did change something between RC2 and RC3 that caused a break.  All the tests pass, but let me know if you have any problems with the new version.  Thanks!

**Pull request closed without merging**
